- name: Launch app servers in az1
  ec2:
    key_name: '{{keypair}}'
    group_id: '{{security_group}}'
    instance_type: '{{instance_type}}'
    image: '{{image}}'
    vpc_subnet_id: '{{vpc_az1_subnet_id}}'
    wait: true
    exact_count: '{{az1_node_count}}'
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 50
        delete_on_termination: true
    monitoring: yes
    instance_tags:
      Name: '{{instance_name_tag_az1}}'
      AppServerAZ1: '{{instance_name_tag_az1}}'
    count_tag: AppServerAZ1
    ec2_url: '{{ec2_url}}'
    aws_access_key: '{{aws_access_key}}'
    aws_secret_key: '{{aws_secret_key}}'
    assign_public_ip: '{{allow_public_access|bool}}'
    region: '{{region}}'
  register: ec2_az1
- name: >-
    Add new instances to host group with public IPs, adding public IP and
    AMI Launch Index as variables in az1 - app servers
  add_host:
    name: '{{item.public_ip}}'
    groups: '{{app_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.public_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az1.tagged_instances}}'
  when: allow_public_access|bool
- name: >-
    Add new instances to host group with private IPs, adding private IP and
    AMI Launch Index as variables in az1 - app servers
  add_host:
    name: '{{item.private_ip}}'
    groups: '{{app_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.private_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az1.tagged_instances}}'
  when: not allow_public_access|bool
- name: >-
    Add new instances to host group with public IPs, adding public IP and
    AMI Launch Index as variables in az1 - web servers
  add_host:
    name: '{{item.public_ip}}'
    groups: '{{web_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.public_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az1.tagged_instances}}'
  when: allow_public_access|bool
- name: >-
    Add new instances to host group with private IPs, adding private IP and
    AMI Launch Index as variables in az1 - web servers
  add_host:
    name: '{{item.private_ip}}'
    groups: '{{web_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.private_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az1.tagged_instances}}'
  when: not allow_public_access|bool
- name: Launch app servers in az2
  ec2:
    key_name: '{{keypair}}'
    group_id: '{{security_group}}'
    instance_type: '{{instance_type}}'
    image: '{{image}}'
    vpc_subnet_id: '{{vpc_az2_subnet_id}}'
    wait: true
    exact_count: '{{az2_node_count}}'
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 50
        delete_on_termination: true
    monitoring: yes
    instance_tags:
      Name: '{{instance_name_tag_az2}}'
      AppServerAZ1: '{{instance_name_tag_az2}}'
    count_tag: AppServerAZ2
    ec2_url: '{{ec2_url}}'
    aws_access_key: '{{aws_access_key}}'
    aws_secret_key: '{{aws_secret_key}}'
    assign_public_ip: '{{allow_public_access|bool}}'
    region: '{{region}}'
  when: az2_node_count|int > 0
  register: ec2_az2      
- name: >-
    Add new instances to host group with public IPs, adding public IP and
    AMI Launch Index as variables in az2 - app servers
  add_host:
    name: '{{item.public_ip}}'
    groups: '{{app_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.public_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az2.tagged_instances}}'
  when: allow_public_access|bool and az2_node_count|int > 0
- name: >-
    Add new instances to host group with private IPs, adding private IP and
    AMI Launch Index as variables in az2 - app servers
  add_host:
    name: '{{item.private_ip}}'
    groups: '{{app_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.private_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az2.tagged_instances}}'
  when: allow_public_access|bool and az2_node_count|int > 0
- name: >-
    Add new instances to host group with public IPs, adding public IP and
    AMI Launch Index as variables in az2 - web servers
  add_host:
    name: '{{item.public_ip}}'
    groups: '{{web_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.public_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az2.tagged_instances}}'
  when: allow_public_access|bool and az2_node_count|int > 0
- name: >-
    Add new instances to host group with private IPs, adding private IP and
    AMI Launch Index as variables in az2 - web servers
  add_host:
    name: '{{item.private_ip}}'
    groups: '{{web_servers_host_group}}'
    private_ip: '{{item.private_ip}}'
    public_ip: '{{item.public_ip}}'
    hostname: '{{item.private_dns_name}}'
    ami_launch_index: '{{item.ami_launch_index}}'
  with_items: '{{ec2_az2.tagged_instances}}'
  when: allow_public_access|bool and az2_node_count|int > 0
- name: Template the ansible host file to use it later
  template:
    src: ./templates/ansible-hosts.j2
    dest: './inventories/{{env}}/auto-created-hosts'
- name: Wait for a while before trying to configure instances
  pause:
    seconds: 60